# common configuration for ALL branches
version: 0.0.{build}
image: Visual Studio 2017
branches:
  only:
    - master
    - develop
environment:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
skip_branch_with_pr: false
configuration:
- Debug
- Release
platform: Any CPU
install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe
before_build:
# Display .NET Core version
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m
  - cmd: nuget restore
build:
  verbosity: minimal
  parallel: true
init:
  - git config --global core.autocrlf input
clone_depth: 1
