# common configuration for ALL branches
version: 0.0.4.{build}
image: Visual Studio 2017
# branches:
  # only:
    # - master
    # - develop
environment:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
skip_branch_with_pr: false
configuration:
- Debug
- Release
platform: Any CPU
clone_depth: 1

init:
  - git config --global core.autocrlf input

install:
  - cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe
  # - ps : .\resetbuildnumber.ps1  
before_build:
- cmd: >-
    dotnet --version

    dotnet restore --verbosity m

    nuget restore

build:
  verbosity: minimal
  parallel: true

test_script:
- cmd: dotnet vstest .\JAH.Data.UnitTests\bin\%configuration%\netcoreapp2.0\JAH.Data.UnitTests.dll .\JAH.Services.UnitTests\bin\%configuration%\netcoreapp2.0\JAH.Services.UnitTests.dll .\JAH.Api.UnitTests\bin\%configuration%\netcoreapp2.0\JAH.Api.UnitTests.dll .\JAH.Web.UnitTests\bin\%configuration%\netcoreapp2.0\JAH.Web.UnitTests.dll .\JAH.Web.IntegrationTests\bin\%configuration%\netcoreapp2.0\JAH.Web.IntegrationTests.dll

# here we are going to override common configuration
for:

# override settings for `master` branch
-
  branches:
    only:
      - master
      - develop
      
  after_build:
    - cmd: dotnet publish JAH.Web\JAH.Web.csproj
    - cmd: dotnet publish JAH.Api\JAH.Api.csproj
    
  artifacts:
    - path: 'JAH.Web\bin\Any CPU\%configuration%\netcoreapp2.0\publish'
      name: WebSite
      type: WebDeployPackage
    - path: 'JAH.Api\bin\Any CPU\%configuration%\netcoreapp2.0\publish'
      name: Api
      type: WebDeployPackage
# "fall back" configuration for all other branches
-
  configuration:
  - Debug
  - Release
