# common configuration for ALL branches
version: 0.0.{build}
image: Visual Studio 2017
branches:
  only:
    - master
    - develop
environment:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
skip_branch_with_pr: false
configuration:
- Debug
- Release
platform: Any CPU
clone_depth: 1

init:
  - git config --global core.autocrlf input

install:
  - cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe
  
before_build:
# Display .NET Core version
  - cmd: dotnet --version
# Display minimal restore text
  - cmd: dotnet restore --verbosity m
#restore nuget packages
  - cmd: nuget restore

build:
  verbosity: minimal
  parallel: true

# here we are going to override common configuration
for:

# override settings for `master` branch
-
  branches:
    only:
      - master

  build_script:
    - cmd: dotnet publish JobApplicationHelper\JobApplicationHelper.csproj
      
  artifacts:
    - path: 'JobApplicationHelper\bin\Any CPU\%configuration%\netcoreapp2.0\publish'
      name: WebSite
      type: WebDeployPackage
